version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: graduation
      MYSQL_USER: rootsll
      MYSQL_PASSWORD: root1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"  # 映射本地端口 6379 到容器的 6379 端口
    volumes:
      - redis-data:/data  # 持久化数据到卷
    restart: always  # 容器崩溃后自动重启

volumes:
  db_data:
  redis-data:  # 定义持久化卷
